name: License Check

on: [push, pull_request]

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install addlicense
        run: |
          go install github.com/google/addlicense@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: "Check license headers"
        run: addlicense -check -l apache -c "PREVOST Corentin" $(find -type f -name "*.go")

