name: lint

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
<<<<<<< HEAD
  lint:
=======
  test:
>>>>>>> eb43e2b (code coverage + linting)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

<<<<<<< HEAD
    - name: Static check
=======
    - name: Run tests
>>>>>>> eb43e2b (code coverage + linting)
      run: go vet ./...
