name: test

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Run tests
      run: |
        go test -v -coverprofile=coverage.out ./...
        grep -Ev '_test\.go|internal/errors' coverage.out > coverage.filtered.out

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.filtered.out
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
